name: GitHub Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""

          # 星标主题插件配置
          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_limit: 15

          # 最近 Star 插件配置
          plugin_stargazers: yes
          plugin_stargazers_limit: 3
          plugin_stargazers_repositories: 100

          # 全年日历插件配置 (新添加)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year